/** Privacy Policy, transcribed verbatim from carfintech.com.au/privacy-policy. */
export type PrivacyBlock = { type: "h2" | "h3" | "p"; text: string } | { type: "list"; items: string[] };

export const privacyPolicy: PrivacyBlock[] = [
  { type: "p", text: "This Privacy Policy sets out our commitment to protecting the privacy of personal information provided to us, or otherwise collected by us, offline or online, including through our website." },
  { type: "p", text: "In this Privacy Policy, \"we\", \"us\" or \"our\" means AUSSIE FINANCIALS PTY LTD ABN 42 652 603 195." },
  { type: "p", text: "We are committed to complying with the Privacy Act 1988 (Cth) and the Australian Privacy Principles (APPs) in our handling of personal information." },
  { type: "h2", text: "What is Personal Information?" },
  { type: "p", text: "Personal information is information or an opinion about an identified individual, or an individual who is reasonably identifiable, whether the information or opinion is true or not, and whether the information or opinion is recorded in a material form or not." },
  { type: "p", text: "Sensitive information is a subset of personal information that is given a higher level of protection under the Australian Privacy Principles. Sensitive information includes information relating to your racial or ethnic origin, political opinions, religion, trade union or other professional associations or memberships, philosophical beliefs, sexual orientation or practices, criminal records, health information or biometric information." },
  { type: "h2", text: "What Personal Information Do We Collect?" },
  { type: "p", text: "The types of personal information we may collect about you include:" },
  {
    type: "list",
    items: [
      "Your name",
      "Your contact details, including email address, mailing address, street address and telephone number",
      "Your age and/or date of birth",
      "Your demographic information, such as postcode",
      "Your preferences and opinions",
      "Information you provide to us through customer surveys or feedback",
      "Details of products and services we have provided to you or that you have enquired about, and our response to you",
      "Your browser session and geo-location data, device and network information, statistics on page views and sessions, acquisition sources, search queries and browsing behaviour",
      "Information about your access and use of our Site, including through the use of Internet cookies, your communications with our Site, the type of browser you are using, the type of operating system you are using and the domain name of your Internet service provider",
      "Additional personal information that you provide to us, directly or indirectly, through your use of our Site, associated applications, associated social media platforms and accounts from which you permit us to collect information",
      "Any other personal information requested by us or provided by you or a third party",
    ],
  },
  { type: "p", text: "We may collect these types of personal information directly from you or from third parties." },
  { type: "h2", text: "How Do We Collect and Store Personal Information?" },
  { type: "h3", text: "How We Collect" },
  { type: "p", text: "We collect personal information in a variety of ways, including:" },
  {
    type: "list",
    items: [
      "When you provide it directly to us, such as when you contact us, make an enquiry, fill out a form, or use our services",
      "When you interact with our Site or use our services",
      "From third parties, such as our business partners, service providers, or publicly available sources",
      "Through our use of cookies and other tracking technologies on our Site",
    ],
  },
  { type: "p", text: "Where reasonable and practical, we will collect your personal information directly from you." },
  { type: "h3", text: "Where We Store" },
  { type: "p", text: "We store personal information in secure physical and electronic formats. This may include:" },
  { type: "list", items: ["Secure servers and databases located in Australia", "Cloud storage services provided by third parties", "Physical records stored securely at our premises"] },
  { type: "p", text: "Some of our service providers may store data outside of Australia. Where this occurs, we take reasonable steps to ensure your information is protected in accordance with the Australian Privacy Principles." },
  { type: "h2", text: "Why Do We Collect, Hold, Use and Disclose Personal Information?" },
  { type: "p", text: "We may collect, hold, use and disclose personal information for the following purposes:" },
  {
    type: "list",
    items: [
      "To enable you to access and use our Site, associated applications and associated social media platforms",
      "To contact and communicate with you about our services",
      "To provide products and services to you",
      "For internal record keeping, administrative, invoicing and billing purposes",
      "For analytics, market research and business development, including to operate and improve our Site, associated applications and associated social media platforms",
      "To run competitions, promotions or offer additional benefits to you",
      "For advertising and marketing, including to send you promotional information about our products and services and information about third parties that we consider may be of interest to you",
      "To comply with our legal obligations and resolve any disputes that we may have",
      "To consider your employment application",
      "Any other purpose for which the information was collected",
    ],
  },
  { type: "h2", text: "Do We Disclose Personal Information to Third Parties?" },
  { type: "p", text: "We may disclose personal information to:" },
  {
    type: "list",
    items: [
      "Third party service providers for the purpose of enabling them to provide their services, including IT service providers, data storage, web-hosting and server providers, maintenance or problem-solving providers, marketing or advertising providers, professional advisors (including accountants, auditors and lawyers), payment systems operators and debt collectors",
      "Our employees, contractors and related entities",
      "Our existing or potential agents or business partners",
      "Sponsors or promoters of any competition we run",
      "Anyone to whom our business or assets (or any part of them) are, or may (in good faith) be, transferred",
      "Credit reporting agencies, courts, tribunals and regulatory authorities, in the event you fail to pay for goods or services we have provided to you",
      "Courts, tribunals, regulatory authorities and law enforcement officers, as required by law, in connection with any actual or prospective legal proceedings, or in order to establish, exercise or defend our legal rights",
      "Third parties, including agents or sub-contractors, who assist us in providing information, products, services or direct marketing to you",
      "Third parties to collect and process data, such as [INSERT ANALYTICS PROVIDERS, e.g., Google Analytics]. This may include parties that store data outside of Australia",
    ],
  },
  { type: "h3", text: "Disclosure to Overseas Recipients" },
  { type: "p", text: "Some of the recipients to whom we disclose your personal information may be based overseas. It is not practicable to list every country in which such recipients are located." },
  { type: "p", text: "By providing us with personal information, you consent to the disclosure of your personal information to third parties who reside outside Australia and acknowledge that we are not required to ensure that those third parties comply with Australian privacy laws." },
  { type: "p", text: "We will, however, take reasonable steps to ensure that any overseas recipient will deal with such personal information in a manner consistent with the APPs." },
  { type: "h2", text: "How Do We Treat Sensitive Information?" },
  { type: "p", text: "We will only collect sensitive information about you with your consent, unless we are required or authorized by law to collect such information." },
  { type: "p", text: "Sensitive information will be used and disclosed only for the purpose for which it was provided or a directly related secondary purpose, unless you otherwise agree, or an exemption under the Privacy Act applies." },
  { type: "h2", text: "Your Rights and Controlling Your Personal Information" },
  { type: "h3", text: "Your Choice and Consent:" },
  { type: "p", text: "By providing personal information to us, you consent to us collecting, holding, using and disclosing your personal information in accordance with this Privacy Policy. You do not have to provide personal information to us, however, if you do not, it may affect your use of our Site or the products and services offered on or through it." },
  { type: "h3", text: "Information from Third Parties:" },
  { type: "p", text: "If we receive personal information about you from a third party, we will protect it as set out in this Privacy Policy. If you are a third party providing personal information about somebody else, you represent and warrant that you have such person's consent to provide the personal information to us." },
  { type: "h3", text: "Marketing Communications:" },
  { type: "p", text: "We may use your personal information to send you direct marketing communications including offers, updates and newsletters that are relevant to the services we provide. We may do so by mail, email, SMS or other electronic means." },
  { type: "p", text: "You can opt-out of receiving marketing communications from us at any time by contacting us using the details below, or by using the opt-out or unsubscribe facilities provided in the communications. We will not charge you for giving effect to your opt-out request." },
  { type: "h3", text: "Restrict or Limit Use:" },
  { type: "p", text: "You may choose to restrict the collection or use of your personal information. If you have previously agreed to us using your personal information for direct marketing purposes, you may change your mind at any time by contacting us using the details below." },
  { type: "h3", text: "Access to Your Personal Information:" },
  { type: "p", text: "You may request access to the personal information that we hold about you. We will respond to your request within a reasonable period. We may charge a reasonable administrative fee for providing access to your personal information." },
  { type: "p", text: "In certain circumstances, as set out in the Privacy Act, we may refuse to provide you with access to your personal information. If we refuse your request, we will provide you with reasons for our refusal." },
  { type: "h3", text: "Correction of Your Personal Information:" },
  { type: "p", text: "If you believe that any information we hold about you is inaccurate, out of date, incomplete, irrelevant or misleading, please contact us using the details below. We will take reasonable steps to correct any information found to be inaccurate, incomplete, misleading or out of date." },
  { type: "p", text: "If we refuse your request to correct your personal information, we will provide you with reasons for our refusal and the mechanisms available to you to complain about our refusal." },
  { type: "h3", text: "Complaints:" },
  { type: "p", text: "If you believe that we have breached the Australian Privacy Principles and wish to make a complaint, please contact us using the details below and provide us with full details of the alleged breach." },
  { type: "p", text: "We will promptly investigate your complaint and respond to you in writing setting out the outcome of our investigation and the steps we will take to deal with your complaint. You also have the right to contact the Office of the Australian Information Commissioner (OAIC) if you wish to make a complaint." },
  { type: "h3", text: "Unsubscribe:" },
  { type: "p", text: "To unsubscribe from our email database or opt-out of communications (including marketing communications), please contact us using the details below or use the opt-out facilities provided in the communication." },
  { type: "h2", text: "How Do We Store and Protect Your Personal Information?" },
  { type: "p", text: "We are committed to ensuring that the personal information we collect is secure. In order to prevent unauthorized access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure personal information and protect it from misuse, interference, loss and unauthorized access, modification and disclosure." },
  { type: "h3", text: "How Long We Keep Your Information:" },
  { type: "p", text: "We retain your personal information only for as long as necessary to fulfill the purposes for which it was collected, or as required by law. This may include retention for legal, accounting, or reporting requirements. We will take all reasonable steps to destroy or permanently de-identify personal information when it is no longer needed for any purpose for which it may be used or disclosed under the Australian Privacy Principles." },
  { type: "h3", text: "Security of Information:" },
  { type: "p", text: "While we take all reasonable steps to protect your personal information, we cannot guarantee the security of any information you transmit to us over the internet. The transmission and exchange of information is carried out at your own risk." },
  { type: "h2", text: "Cookies and Web Beacons" },
  { type: "p", text: "We may use cookies on our Site from time to time. Cookies are text files placed in your computer's browser to store your preferences. Cookies, by themselves, do not tell us your email address or other personally identifiable information. However, they do allow third parties, such as Google and Facebook, to cause our advertisements to appear on your social media and online media feeds as part of our retargeting campaigns." },
  { type: "p", text: "If and when you choose to provide our Site with personal information, this information may be linked to the data stored in the cookie." },
  { type: "p", text: "We may use web beacons on our Site from time to time. Web beacons (also known as Clear GIFs or pixel tags) are small pieces of code placed on a web page to monitor the visitor's behaviour and collect data about the visitor's viewing of a web page. For example, web beacons can be used to count the users who visit a web page or to deliver a cookie to the browser of a visitor viewing that page." },
  { type: "p", text: "You can control and manage cookies through your browser settings. However, disabling cookies may affect the functionality and features of our Site." },
  { type: "h2", text: "Links to Other Websites" },
  { type: "p", text: "Our Site may contain links to other websites. We do not have any control over those websites and we are not responsible for the protection and privacy of any personal information which you provide whilst visiting those websites. Those websites are not governed by this Privacy Policy." },
  { type: "h2", text: "Business Without Identifying You" },
  { type: "p", text: "Where it is lawful and practicable, you may have the option of dealing with us anonymously or by using a pseudonym. However, in most circumstances it will be necessary for us to identify you in order to successfully provide our services to you." },
  { type: "h2", text: "Updates to This Privacy Policy" },
  { type: "p", text: "We may, at any time and at our discretion, vary this Privacy Policy by publishing the amended Privacy Policy on our Site. We recommend you check our Site regularly to ensure you are aware of our current Privacy Policy." },
  { type: "p", text: "Your continued use of our Site and services following any changes to this Privacy Policy will be taken to indicate your acceptance of those changes." },
  { type: "h2", text: "Contact Us" },
  { type: "p", text: "For any questions, concerns, or notices regarding this Privacy Policy, or to make a request to access or correct your personal information, or to make a complaint, please contact our Privacy Officer at: Car Fintech" },
];

export const privacyContact = {
  email: "chirag@carfintech.com.au",
  phone: { display: "0415 600 002", tel: "+61415600002" },
  address: "Melbourne, VIC",
  oaic: { name: "Office of the Australian Information Commissioner (OAIC)", website: "www.oaic.gov.au", phone: "1300 363 992" },
};
